#!/usr/bin/with-contenv bash
set -e

EXTENSIONS_DIR="/config/extensions"
EXTENSION_VSIX_DIR="/usr/local/share/code-server/extensions"
EXTENSION_IDS="
openai.chatgpt
muhammad-sammy.csharp
"
EXTENSION_VSIXES="
divanvisagie.nord-native-theme|${EXTENSION_VSIX_DIR}/divanvisagie.nord-native-theme.vsix
"

for EXTENSION_ID in ${EXTENSION_IDS}; do
    if s6-setuidgid abc code-server --list-extensions --extensions-dir "${EXTENSIONS_DIR}" | grep -Fxq "${EXTENSION_ID}"; then
        echo "[custom-init] ${EXTENSION_ID} already installed"
    else
        echo "[custom-init] Installing ${EXTENSION_ID}"
        s6-setuidgid abc code-server --install-extension "${EXTENSION_ID}" --extensions-dir "${EXTENSIONS_DIR}"
    fi
done

for EXTENSION_VSIX in ${EXTENSION_VSIXES}; do
    EXTENSION_ID="${EXTENSION_VSIX%%|*}"
    EXTENSION_PATH="${EXTENSION_VSIX#*|}"

    if s6-setuidgid abc code-server --list-extensions --extensions-dir "${EXTENSIONS_DIR}" | grep -Fxq "${EXTENSION_ID}"; then
        echo "[custom-init] ${EXTENSION_ID} already installed"
    else
        echo "[custom-init] Installing ${EXTENSION_ID}"
        s6-setuidgid abc code-server --install-extension "${EXTENSION_PATH}" --extensions-dir "${EXTENSIONS_DIR}"
    fi
done
